### ISSUE TITLE
frontends/polling.py missing

### ISSUE THREAD

**Issue by norwood867** [kcallin/haka-mqtt#21]
the directory frontends is missing in the build.

**Comment by kcallin** [comment]
I downloaded the package from pypi at https://files.pythonhosted.org/packages/53/b0/d822ba40ca0cce1e947759ed478cf400035e6d741a447d6b7555e6bf048f/haka-mqtt-0.3.1.tar.gz and found that the archive does not contain the file haka_mqtt/frontends/poll.py as expected.

I plan to release 0.3.2, perhaps tomorrow, that includes the file.  Meanwhile the file is available at https://github.com/kcallin/haka-mqtt/blob/master/haka_mqtt/frontends/poll.py.

Just a point of curiosity, the ticket says "polling.py".  I expected the file to be named "poll.py".  Did I describe it as "polling.py" in the documentation somewhere?

**Comment by kcallin** [comment]
Fixed in 0.3.2 release.

**Comment by norwood867** [comment]
hi. i couldn't find a play you said polling.py so it must of been my
mistake.

thanks for fixing the issue.

**Comment by kcallin** [comment]
No problem.  I hope it works out for you.
